# Generated by Django 4.2.20 on 2025-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallzone', '0002_remove_category_slug_category_image_wallpaper_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ManyToManyField(related_name='wallpapers', to='wallzone.category'),
        ),
    ]
