# Generated by Django 4.2.20 on 2025-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallzone', '0003_alter_wallpaper_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='image',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='original_file_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='thumbnail_file_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
