# Generated by Django 4.2.20 on 2025-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallzone', '0004_remove_wallpaper_image_wallpaper_original_file_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='location',
            field=models.IntegerField(choices=[(1, 'Local'), (2, 'S3'), (3, 'Other')], default=1),
        ),
    ]
